Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  4.0.173.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Constituent Timeline' data form
''' </summary>
Partial Public Class [ConstituentTimelineUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _contextid As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")> _
    Public Sub New()
        MyBase.New()

        _contextid = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.FORMHEADER.Value = "Constituent Timeline"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/shared/timeline/ConstituentTimeLineUIModel.html"

        '
        '_contextid
        '
        _contextid.Name = "CONTEXTID"
        _contextid.Caption = "Context ID"
        _contextid.MaxLength = 40
        Me.Fields.Add(_contextid)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Context ID
    ''' </summary>
    <System.ComponentModel.Description("Context ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")> _
    Public ReadOnly Property [CONTEXTID]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _contextid
        End Get
    End Property
    
End Class
